# Generated by Django 5.1.3 on 2024-11-15 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=9)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('transactionType', models.CharField(choices=[('WTD', 'withdraw transaction'), ('DEP', 'deposit transaction'), ('TRAN', 'transfer transaction')], max_length=20)),
                ('transfer_to_account', models.CharField(blank=True, max_length=30, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.account')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
