# Generated by Django 5.1.2 on 2024-11-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bank_site',
            field=models.CharField(default='default_value', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='client_documents',
            field=models.FileField(default='', upload_to='client_documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(default='', upload_to='client_images/'),
            preserve_default=False,
        ),
    ]
